version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshop_jpa_springboot
    ports:
      - "8080:9000"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}