version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: workshop-jpa-springboot
    restart: always
    container_name: workshop-jpa-springboot-container
    ports:
      - "9000:8080"