FROM maven:3.8.3-openjdk-17 AS build
COPY . .
RUN mvn clean packege -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=build /target/courseproject-0.0.1-SNAPSHOT.jar courseproject.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","courseproject.jar" ]