INSERT INTO public.tb_category(
	id, name)
	VALUES
	  (1, 'Food'),
	  (2, 'Housing'),
	  (3, 'Clothing'),
	  (4, 'Electronics'),
	  (5, 'Furniture'),
	  (6, 'Books'),
	  (7, 'Health and Beauty'),
	  (8, 'Toys and Games'),
	  (9, 'Sports and Outdoors'),
	  (10, 'Automotive'),
	  (11, 'Music'),
	  (12, 'Movies'),
	  (13, 'Travel'),
	  (14, 'Home Improvement'),
	  (15, 'Jewelry'),
	  (16, 'Pet Supplies'),
	  (17, 'Office Supplies'),
	  (18, 'Garden and Outdoor'),
	  (19, 'Appliances'),
	  (20, 'Tools'),
	  (21, 'Baby and Kids'),
	  (22, 'Crafts and Hobbies'),
	  (23, 'Fitness'),
	  (24, 'Gifts and Collectibles'),
	  (25, 'Party and Celebrations'),
	  (26, 'Photography'),
	  (27, 'Business and Industrial'),
	  (28, 'Education'),
	  (29, 'Technology'),
	  (30, 'Art and Design');